### PR TITLE
Decode variables in AC1.50

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
These variables are valid from AC1.50 to AC1009

### CODE REVIEW

**Review by rurban — APPROVED** [review]

**Comment by michal-josef-spacek** [comment]
@rurban How is working output like 16b0c8b126d94463a9fb75aa825e45d7278f77db..4a16f42c557eb35e1ab67bf69ff85228c004d65b ? Is this code autogenerated or written?

**Comment by rurban** [comment]
make regen-dynapi

**Comment by michal-josef-spacek** [comment]
@rurban 
When i am using configure then `make regen-dynapi` causes error:
```
woman:~libredwg> make regen-dynapi
/usr/bin/perl ./src/gen-dynapi.pl
using gcc with /usr/lib/gcc/x86_64-linux-gnu/8/include
Cannot find input file '../include/dwg.h' at ./src/gen-dynapi.pl line 82.
make: [Makefile:1244: regen-dynapi] Chyba 2 (ignorováno)
```

**Comment by rurban** [comment]
I only tested it via ../configure in a build dir.
Otherwise you need a special perl call, and a Makefile fix

**Comment by rurban** [comment]
Already merged

**Pull request closed without merging**
