### PR TITLE
Fix TILEMODE header variables in preR13

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by rurban** [comment]
RS really for a boolean?
Several more fixes for the removal needed. make check helps

**Comment by michal-josef-spacek** [comment]
@rurban I think yes. Seems three RS variables in a row. I could set a bigger value for PLINECHECK and it's in DXF from AutoCAD.

I'm trying to figure out the value after PLINECHECK. It's in model space 0/1, but don't know what it's. If the number is bigger, it's cleared to "01 00" by AutoCAD.

The alternative version could be theoretically RC RC RS RC RC, but there are more variables than a number of variables in the header. I am for RS RS RS now.

**Review by rurban — CHANGES_REQUESTED** [review]
And now just as in the next line. Cast the RS to B

**Comment by rurban** [comment]
Merged, slightly fixed. Thanks!

**Pull request closed without merging**
