### PR TITLE
Unify conversion units

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by rurban** [comment]
I would rather name them unit1-4_ratio and unit1-4_text

**Review by rurban — CHANGES_REQUESTED** [review]
I would rather name them unit[1-4] _ratio and unit[1-4]_name

**Comment by michal-josef-spacek** [comment]
@rurban ok, i will look to it.

**Comment by michal-josef-spacek** [comment]
Updated (AC1009 example):
```
unit1_ratio: 412148564080.000000 [RD 0]
unit2_ratio: 0.000000 [RD 0]
unit3_ratio: 16226321420472.441406 [RD 0]
unit4_ratio: 263293506840482798429536256.000000 [RD 0]
unit1_name: "meter" [TFv 32 1]
6D65746572000000000000000000000000000000000000000000000000000000
unit2_name: "inch" [TFv 32 1]
696E636800000000000000000000000000000000000000000000000000000000
unit3_name: "inch" [TFv 32 1]
696E636800000000000000000000000000000000000000000000000000000000
unit4_name: "sq inch" [TFv 32 1]
737120696E636800000000000000000000000000000000000000000000000000
```

**Comment by michal-josef-spacek** [comment]
It's nice

**Comment by michal-josef-spacek** [comment]
plus make regen-dynapi

**Pull request closed without merging**
