### PR TITLE
Remove zero_5 variable

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
This is about simplification of the header (and second header). It's for all DWG versions.

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
I tested on all DWGs which I have, I tested JSON and DWG.

**Comment by rurban** [comment]
Well, it removes the information that the version is of max length 8. but on the other side, it is most likely that the real code is more like that. So good enough

**Comment by michal-josef-spacek** [comment]
There is probably a need for regen and doc.  

About JSONs: This is an interesting thing because JSON is not backward compatible in any way in the development process. I know there are many issues with structures (e.g. aux header is very problematic, and I don't see a way to fix still). This means there will be changes in JSON in the future.

**Comment by michal-josef-spacek** [comment]
btw: I am planning some changes:
* I want to change is_maint to something better because this is "the maintenance version". The word "is" isn't right.
* I want to change dwg_version and maint_version, it is the version of AutoCAD in real, so something saved_by_autocad should be better. Seems that's one variable because of the BS in the Second Header. Probably better is to use the structure. Probably related to understand aux header.

**Pull request merged**
