### PR TITLE
Add tests for dwg_find_color_index()

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
The failure in mingw:
```
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../src/.libs/libredwg.dll.a(libredwg_0_dll_d000226.o):(.text+0x0): multiple definition of `dwg_find_color_index'; ../../src/.libs/dwg.o:D:/a/libredwg/libredwg/src/dwg.c:3013: first defined here
```
I don't know how to test and fix

**Comment by rurban** [comment]
It's already exported. No need to link it again

**Comment by michal-josef-spacek** [comment]
@rurban btw: in rgb_palette[256] is { 0xFF, 0xFF, 0xFF } two times (index 7 and 255).

**Comment by rurban** [comment]
> @rurban btw: in rgb_palette[256] is { 0xFF, 0xFF, 0xFF } two times (index 7 and 255).

Yes, on purpose. It's the default color

**Comment by rurban** [comment]
Merged with fixups

**Pull request closed without merging**
