### PR TITLE
Fix dimension entity

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by rurban** [comment]
This breaks all r10 dimensions, lots of offset errors

```
tutorial_from_autocad_r10_xenix_r10.log-def_pt: (200.000000, 290.000000, 0.000000) [3RD 10]
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (173.900000, 290.000000) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log-xline1_pt: (100.000000, 0.000000, 232.000000) [3RD 13]
tutorial_from_autocad_r10_xenix_r10.log-xline2_pt: (229.000000, 0.000000, 200.000000) [3RD 14]
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 16
--
tutorial_from_autocad_r10_xenix_r10.log-def_pt: (254.000000, 110.000000, 0.000000) [3RD 10]
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (280.100000, 110.000000) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log-xline1_pt: (100.000000, 0.000000, 232.000000) [3RD 13]
tutorial_from_autocad_r10_xenix_r10.log-xline2_pt: (171.000000, 0.000000, 254.000000) [3RD 14]
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 16
--
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (110.000000, 200.000000) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log-xline1_pt: (100.000000, 0.000000, 232.000000) [3RD 13]
tutorial_from_autocad_r10_xenix_r10.log-xline2_pt: (171.000000, 0.000000, 232.000000) [3RD 14]
tutorial_from_autocad_r10_xenix_r10.log-dim_rotation: 229.000000 [RD 50]
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 16
--
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (320.000000, 200.000000) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log-xline1_pt: (100.000000, 0.000000, 274.000000) [3RD 13]
tutorial_from_autocad_r10_xenix_r10.log-xline2_pt: (251.000000, 0.000000, 274.000000) [3RD 14]
tutorial_from_autocad_r10_xenix_r10.log-dim_rotation: 149.000000 [RD 50]
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 16
--
tutorial_from_autocad_r10_xenix_r10.log-def_pt: (274.000000, 90.000000, 0.000000) [3RD 10]
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (299.650000, 90.000000) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log-xline1_pt: (100.000000, 0.000000, 254.000000) [3RD 13]
tutorial_from_autocad_r10_xenix_r10.log-xline2_pt: (52.000000, 0.000000, 274.000000) [3RD 14]
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 16
--
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (110.000000, 37.000000) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log-xline1_pt: (100.000000, 0.000000, 254.000000) [3RD 13]
tutorial_from_autocad_r10_xenix_r10.log-xline2_pt: (52.000000, 0.000000, 178.000000) [3RD 14]
tutorial_from_autocad_r10_xenix_r10.log-dim_rotation: 22.000000 [RD 50]
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 16
--
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (125.750000, 11.200000) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log-xline1_pt: (100.000000, 0.000000, 178.000000) [3RD 13]
tutorial_from_autocad_r10_xenix_r10.log-xline2_pt: (42.000000, 0.000000, 178.000000) [3RD 14]
tutorial_from_autocad_r10_xenix_r10.log-dim_rotation: 22.000000 [RD 50]
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 16
--
tutorial_from_autocad_r10_xenix_r10.log-block: 7 [H(RSd) 2]
tutorial_from_autocad_r10_xenix_r10.log-def_pt: (200.000000, 200.000000, 0.000000) [3RD 10]
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (142.801997, 222.532002) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-flag: 0x0 [RC 70]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 48
--
tutorial_from_autocad_r10_xenix_r10.log-block: 8 [H(RSd) 2]
tutorial_from_autocad_r10_xenix_r10.log-def_pt: (232.000000, 171.000000, 0.000000) [3RD 10]
tutorial_from_autocad_r10_xenix_r10.log-text_midpt: (175.528797, 130.842111) [2RD 11]
tutorial_from_autocad_r10_xenix_r10.log-flag: 0x0 [RC 70]
tutorial_from_autocad_r10_xenix_r10.log-=> Entity DIMENSION_LINEAR
tutorial_from_autocad_r10_xenix_r10.log:ERROR: offset 48
```

**Comment by michal-josef-spacek** [comment]
> Still lots of offset errors in r10. But it was broken before also

Interesting, I haven't errors. I am going to cleanup the build and again.

**Comment by michal-josef-spacek** [comment]
> > Still lots of offset errors in r10. But it was broken before also
> 
> Interesting, I haven't errors. I am going to cleanup the build and again.

ah, I see. Looking to it.

**Comment by michal-josef-spacek** [comment]
Two fixes, I know about another one (field is dimstyle index probably)

**Comment by rurban** [comment]
Still a RS missing, with the opts 0x8000 flag. with ordinate, radius, linear
Eg.  TUTORIAL_from_autocad_r11_r11.log
```
Add entity DIMENSION_ANG2LN [49] ===========================
Entity number: 49, Type: 23, Addr: edb
flag_r11: 0x0 [RC 0]
size: 103 [RS]
layer: 3 [H(RSd) 8]
opts_r11: 0x80a3 [RSx 0]
          HAS_DXF12 (1) HAS_FLAG (2) HAS_DXF15 (32) HAS_DXF40 (128) Warning: Unknown opts_r11 (32931)
block: 8 [H(RSd) 2]
def_pt: (200.000000, 200.000000, 0.000000) [3RD 10]
text_midpt: (156.127697, 223.608876) [2RD 11]
clone_ins_pt: (274.000000, 48.769398) [2RD 12]
flag: 0x4 [RC 70]
=> Entity DIMENSION_RADIUS
first_arc_pt: (179.611106, 208.263958, 0.000000) [3RD 15]
leader_len: 12.227750 [RD 40]
ERROR: offset 2
crc: DB3E [RSx]
```

**Comment by rurban** [comment]
I've rebased it on top of "fix dwg_sections_init: renamed, fuzzing GH 581"

**Comment by rurban** [comment]
Merged

**Pull request closed without merging**
