### PR TITLE
Add common preR13 POLYLINE_R11 and VERTEX_R11 entities

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
For https://github.com/LibreDWG/libredwg/issues/722

### CODE REVIEW

**Review by rurban — CHANGES_REQUESTED** [review]
unit-tests are missing

**Comment by rurban** [comment]
what are the numverts, numfaces flags and fields for the polyline pface variant?
shared with num_{n,m}_verts?

**Comment by michal-josef-spacek** [comment]
> what are the numverts, numfaces flags and fields for the polyline pface variant? shared with num_{n,m}_verts?

Yes

Example:
```
Add entity POLYLINE_R11 [13] Decode entity POLYLINE_R11
===========================
Entity number: 13, Type: 19, Addr: 6cf
flag_r11: 0xa0 [RC 0]
          HAS_HANDLING(0x20) HAS_ATTRIBS(0x80)
size: 17 [RS]
layer: 0 [H(RSd) 8]
opts_r11: 0x31 [RSx 0]
          HAS_FLAG(0x1) HAS_M_VERTS(0x10) HAS_N_VERTS(0x20)
handle: 0.1.20 [H 5]
flag: 0x40 [RC 70]
      PFACE_MESH(0x40)
num_m_verts: 1 [RS 71]
num_n_verts: 1 [RS 72]
crc: BE41 [RSx]
 check_CRC 1743-1758 = 15: BE41 == BE41
[existing handleref (3.2.20) abs:32] BLOCK_HEADER "*MODEL_SPACE".entities[0] = (3.2.20) abs:32 [H]
[add handleref (8.2.0) abs:31] ownerhandle: [2, 0, 1F]
```

```
  0
POLYLINE
  5
20
  8
0
 66
     1
 10
0.0
 20
0.0
 30
0.0
 70
    64
 71
     1
 72
     1
```

**Comment by michal-josef-spacek** [comment]
> unit-tests are missing

Finishing

**Comment by rurban** [comment]
> > what are the numverts, numfaces flags and fields for the polyline pface variant? shared with num_{n,m}_verts?
> 
> Yes
> 
> Example:
> 
> ```
> Add entity POLYLINE_R11 [13] Decode entity POLYLINE_R11
> ===========================
> Entity number: 13, Type: 19, Addr: 6cf
> flag_r11: 0xa0 [RC 0]
>           HAS_HANDLING(0x20) HAS_ATTRIBS(0x80)
> size: 17 [RS]
> layer: 0 [H(RSd) 8]
> opts_r11: 0x31 [RSx 0]
>           HAS_FLAG(0x1) HAS_M_VERTS(0x10) HAS_N_VERTS(0x20)
> handle: 0.1.20 [H 5]
> flag: 0x40 [RC 70]
>       PFACE_MESH(0x40)
> num_m_verts: 1 [RS 71]
> num_n_verts: 1 [RS 72]
> crc: BE41 [RSx]
>  check_CRC 1743-1758 = 15: BE41 == BE41
> [existing handleref (3.2.20) abs:32] BLOCK_HEADER "*MODEL_SPACE".entities[0] = (3.2.20) abs:32 [H]
> [add handleref (8.2.0) abs:31] ownerhandle: [2, 0, 1F]
> ```
> 
> ```
>   0
> POLYLINE
>   5
> 20
>   8
> 0
>  66
>      1
>  10
> 0.0
>  20
> 0.0
>  30
> 0.0
>  70
>     64
>  71
>      1
>  72
>      1
> ```

That's a mesh, not a pface

**Comment by michal-josef-spacek** [comment]
Another type is:
```
Add entity POLYLINE_R11 [13] Decode entity POLYLINE_R11
===========================
Entity number: 13, Type: 19, Addr: 6cf
flag_r11: 0xa0 [RC 0]
          HAS_HANDLING(0x20) HAS_ATTRIBS(0x80)
size: 23 [RS]
layer: 0 [H(RSd) 8]
opts_r11: 0x1f1 [RSx 0]
          HAS_FLAG(0x1) HAS_M_VERTS(0x10) HAS_N_VERTS(0x20) HAS_M_DENSITY(0x40) HAS_N_DENSITY(0x80) HAS_CURVETYPE(0x100)
handle: 0.1.26 [H 5]
flag: 0x14 [RC 70]
      SPLINE_FIT(0x4) MESH(0x10)
num_m_verts: 3 [RS 71]
num_n_verts: 3 [RS 72]
m_density: 7 [RS 73]
n_density: 7 [RS 74]
curve_type: 5 [RS 75]
            QUADR_BSPLINE(0x5)
crc: AA50 [RSx]
 check_CRC 1743-1764 = 21: AA50 == AA50
[add handleref (3.2.26) abs:38] BLOCK_HEADER "*MODEL_SPACE".entities[0] = (3.2.26) abs:38 [H]
[add handleref (12.2.7) abs:31] ownerhandle: [2, 0, 1F]
```

```
  0
POLYLINE
  5
26
  8
0
 66
     1
 10
0.0
 20
0.0
 30
0.0
 70
    20
 71
     3
 72
     3
 73
     7
 74
     7
 75
     5
```

**Comment by michal-josef-spacek** [comment]
Another is:
```
Add entity POLYLINE_R11 [13] Decode entity POLYLINE_R11
===========================
Entity number: 13, Type: 19, Addr: 6cf
flag_r11: 0x80 [RC 0]
          HAS_ATTRIBS(0x80)
size: 11 [RS]
layer: 0 [H(RSd) 8]
opts_r11: 0x1 [RSx 0]
          HAS_FLAG(0x1)
object_map{22} = 13
=> handle: (0.1.22)
flag: 0x8 [RC 70]
      3D(0x8)
crc: 536A [RSx]
 check_CRC 1743-1752 = 9: 536A == 536A
[add handleref (3.2.22) abs:34] BLOCK_HEADER "*MODEL_SPACE".entities[0] = (3.2.22) abs:34 [H]
[add handleref (12.2.3) abs:31] ownerhandle: [2, 0, 1F]
```

```
  0
POLYLINE
  5
24
  8
0
 66
     1
 10
0.0
 20
0.0
 30
0.0
 70
     8
```

**Comment by michal-josef-spacek** [comment]
Another type:
```
Add entity POLYLINE_R11 [13] Decode entity POLYLINE_R11
===========================
Entity number: 13, Type: 19, Addr: 6cf
flag_r11: 0x80 [RC 0]
          HAS_ATTRIBS(0x80)
size: 13 [RS]
layer: 0 [H(RSd) 8]
opts_r11: 0x101 [RSx 0]
          HAS_FLAG(0x1) HAS_CURVETYPE(0x100)
object_map{22} = 13
=> handle: (0.1.22)
flag: 0x4 [RC 70]
      SPLINE_FIT(0x4)
curve_type: 6 [RS 75]
            CUBIC_BSPLINE(0x6)
crc: 6287 [RSx]
 check_CRC 1743-1754 = 11: 6287 == 6287
[add handleref (3.2.22) abs:34] BLOCK_HEADER "*MODEL_SPACE".entities[0] = (3.2.22) abs:34 [H]
[add handleref (12.2.3) abs:31] ownerhandle: [2, 0, 1F]
```

```
  0
POLYLINE
  8
0
 66
     1
 10
0.0
 20
0.0
 30
0.0
 70
     4
 75
     6
```

**Comment by rurban** [comment]
I"m also still not sure if this a good idea, or we just a POLYLINE_R11 macro to the spec.
This way we cannot easily up- or downgrade versions. (e.g. save as r11)

**Comment by michal-josef-spacek** [comment]
Another type:
```
Add entity POLYLINE_R11 [13] Decode entity POLYLINE_R11
===========================
Entity number: 13, Type: 19, Addr: 6cf
flag_r11: 0xa0 [RC 0]
          HAS_HANDLING(0x20) HAS_ATTRIBS(0x80)
size: 23 [RS]
layer: 0 [H(RSd) 8]
opts_r11: 0x1f1 [RSx 0]
          HAS_FLAG(0x1) HAS_M_VERTS(0x10) HAS_N_VERTS(0x20) HAS_M_DENSITY(0x40) HAS_N_DENSITY(0x80) HAS_CURVETYPE(0x100)
handle: 0.1.26 [H 5]
flag: 0x14 [RC 70]
      SPLINE_FIT(0x4) MESH(0x10)
num_m_verts: 3 [RS 71]
num_n_verts: 3 [RS 72]
m_density: 7 [RS 73]
n_density: 7 [RS 74]
curve_type: 5 [RS 75]
            QUADR_BSPLINE(0x5)
crc: AA50 [RSx]
 check_CRC 1743-1764 = 21: AA50 == AA50
[add handleref (3.2.26) abs:38] BLOCK_HEADER "*MODEL_SPACE".entities[0] = (3.2.26) abs:38 [H]
[add handleref (12.2.7) abs:31] ownerhandle: [2, 0, 1F]
```

```
  0
POLYLINE
  5
26
  8
0
 66
     1
 10
0.0
 20
0.0
 30
0.0
 70
    20
 71
     3
 72
     3
 73
     7
 74
     7
 75
     5
```

**Comment by michal-josef-spacek** [comment]
> I"m also still not sure if this a good idea, or we just a POLYLINE_R11 macro to the spec. This way we cannot easily up- or downgrade versions. (e.g. save as r11)

I think that we could simply implement conversion between these types.
This version is better for me.

**Comment by rurban** [comment]
No, with macros it's simplier and easier.
See branch work/r11-pline-macro

**Comment by rurban** [comment]
Still thinking about it though...

**Comment by michal-josef-spacek** [comment]
I will test it.

**Pull request closed without merging**
