### PR TITLE
rename the _R11 Dwg_Object_Type_r11 type values to _r11

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
Rename the _R11 Dwg_Object_Type_r11 type values to _r11, to avoid conflicts with the POLYLINE_R11 fixedtype.

This is preparation to add POLYLINE_R11 entity

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
@rurban Could you regen bindings? I don't know how to regen.

**Comment by michal-josef-spacek** [comment]
@rurban Could we merge?

**Comment by rurban** [comment]
Wait a bit. Just did a massive size_t refactoring, and want to fix deleted preR13 entities first

**Comment by michal-josef-spacek** [comment]
@rurban ok, thanks.

FYI: I am working on another PR based on that.

**Comment by michal-josef-spacek** [comment]
rebased

**Comment by rurban** [comment]
I'm now in Cannes for the festival, and will continue end of may

**Comment by michal-josef-spacek** [comment]
@rurban What about this PR? :-)

**Comment by rurban** [comment]
soon...

**Comment by rurban** [comment]
so this is the next, now

**Review by rurban — APPROVED** [review]

**Pull request merged**
