### PR TITLE
Fix dictionarywdflt

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
@rurban What about this PR? Do you need some examples? :-)

**Comment by rurban** [comment]
I try to remember why I added this quirks at all. Example would be nice, yes

**Comment by michal-josef-spacek** [comment]
btw: I think that is copy/paste of DICTIONARY.

**Comment by michal-josef-spacek** [comment]
I found object in AC1012, AC1014, AC1015
Saved by AutoCAD2000. I don't find any other interpretation of the object.
Examples:
[AC1012_from_autocad2000.dwg.gz](https://github.com/LibreDWG/libredwg/files/14850239/AC1012_from_autocad2000.dwg.gz)
[AC1014_from_autocad_2000.dwg.gz](https://github.com/LibreDWG/libredwg/files/14850240/AC1014_from_autocad_2000.dwg.gz)
[AC1015_from_autocad_2000.dwg.gz](https://github.com/LibreDWG/libredwg/files/14850241/AC1015_from_autocad_2000.dwg.gz)

Before change:
AC1012_from_autocad2000.dwg:
```
Next object: 12 Handleoff: 0x1 [UMC] Offset: -2964 [MC] @20000
==========================================
Object number: 12/C, Size: 53 [MS], Type: 500 [BS], Address: 20002
Add object DICTIONARYWDFLT [12] Decode object DICTIONARYWDFLT
handle: 0.1.E [H 5]
EED[0] size: 20 [BS]
EED[0] handle: 5.1.12
EED[0] raw: 20
EED[0] code: 0 [RC], string: len=13 [RC] cp=28 [RS_BE] "TREAT_AS_HARD" [TF]
EED[1] code: 70 [RC], short: 0 [RS]

EED[2] size: 0 (end)
num_eed: 2
bitsize: 350 [RL]
 Hdlsize: 0x4A, hdl_dat: @43.6 - @53.0 (53)
num_reactors: 1 [BL 0]
ownerhandle: (12.1.2) abs:12 [H 330]
reactors[0]: (4.1.C) abs:12 [H* 330] => DICTIONARY
xdicobjhandle: (3.0.0) abs:0 [H 360]
--common_size: 246
numitems: 1 [BL 0]
TV-ZERO 1
texts[0]: "" [TV 3]
 handle stream: +58 @36.4 MISSING (@43.6  @48.6)
itemhandles[0]: (2.1.F) abs:15 [H* 0]
defaultid: (5.1.F) abs:15 [H 340]
 padding: +2
 object_map{E} = 12
 padding: 3D/1 (2 bits)
crc: 2A2B [RSx]
 check_CRC 20000-20055 = 55: 2A2B == 2A2B
```
AC1014_from_autocad_2000.dwg:
```
Next object: 12 Handleoff: 0x1 [UMC] Offset: -2919 [MC] @19874
==========================================
Object number: 12/C, Size: 30 [MS], Type: 500 [BS], Address: 19876
Add object DICTIONARYWDFLT [12] Decode object DICTIONARYWDFLT
handle: 0.1.E [H 5]
EED[0] size: 0 (end)
num_eed: 0
bitsize: 164 [RL]
 Hdlsize: 0x4C, hdl_dat: @20.4 - @30.0 (30)
num_reactors: 1 [BL 0]
ownerhandle: (12.1.2) abs:12 [H 330]
reactors[0]: (4.1.C) abs:12 [H* 330] => DICTIONARY
xdicobjhandle: (3.0.0) abs:0 [H 360]
--common_size: 60
numitems: 1 [BL 0]
is_hardowner: 0x40 [RC 280]
texts[0]: "" [TV 3]
 handle stream: +58 @13.2 MISSING (@20.4  @25.4)
itemhandles[0]: (2.1.F) abs:15 [H* 0]
defaultid: (5.1.F) abs:15 [H 340]
 padding: +4
 object_map{E} = 12
 padding: F5/5 (4 bits)
crc: BE26 [RSx]
 check_CRC 19874-19906 = 32: BE26 == BE26
```
AC1015_from_autocad_2000.dwg:
```
Next object: 12 Handleoff: 0x1 [UMC] Offset: -1451 [MC] @20458
==========================================
Object number: 12/C, Size: 30 [MS], Type: 500 [BS], Address: 20460
Add object DICTIONARYWDFLT [12] Decode object DICTIONARYWDFLT
bitsize: 164 [RL] @4.2
 Hdlsize: 0x4C, hdl_dat: @20.4 - @30.0 (30)
handle: 0.1.E [H 5]
EED[0] size: 0 (end)
num_eed: 0
num_reactors: 1 [BL 0]
ownerhandle: (12.1.2) abs:12 [H 330]
reactors[0]: (4.1.C) abs:12 [H* 330] => DICTIONARY
xdicobjhandle: (3.0.0) abs:0 [H 360]
--common_size: 60
numitems: 1 [BL 0]
cloning: 1 [BS 281]
is_hardowner: 0x0 [RC 280]
texts[0]: "Normal" [TV 3]
itemhandles[0]: (2.1.F) abs:15 [H* 0]
defaultid: (5.1.F) abs:15 [H 340]
 padding: +4
 object_map{E} = 12
 padding: F1/1 (4 bits)
crc: 77B7 [RSx]
 check_CRC 20458-20490 = 32: 77B7 == 77B7
```

After change:
AC1012_from_autocad2000.dwg:
```
Next object: 12 Handleoff: 0x1 [UMC] Offset: -2964 [MC] @20000
==========================================
Object number: 12/C, Size: 53 [MS], Type: 500 [BS], Address: 20002
Add object DICTIONARYWDFLT [12] Decode object DICTIONARYWDFLT
handle: 0.1.E [H 5]
EED[0] size: 20 [BS]
EED[0] handle: 5.1.12
EED[0] raw: 20
EED[0] code: 0 [RC], string: len=13 [RC] cp=28 [RS_BE] "TREAT_AS_HARD" [TF]
EED[1] code: 70 [RC], short: 0 [RS]

EED[2] size: 0 (end)
num_eed: 2
bitsize: 350 [RL]
 Hdlsize: 0x4A, hdl_dat: @43.6 - @53.0 (53)
num_reactors: 1 [BL 0]
ownerhandle: (12.1.2) abs:12 [H 330]
reactors[0]: (4.1.C) abs:12 [H* 330] => DICTIONARY
xdicobjhandle: (3.0.0) abs:0 [H 360]
--common_size: 246
numitems: 1 [BL 0]
cloning: 1 [BS 281]
is_hardowner: 0x0 [RC 280]
texts[0]: "Normal" [TV 3]
itemhandles[0]: (2.1.F) abs:15 [H* 0]
defaultid: (5.1.F) abs:15 [H 340]
 padding: +2
 object_map{E} = 12
 padding: 3D/1 (2 bits)
crc: 2A2B [RSx]
 check_CRC 20000-20055 = 55: 2A2B == 2A2B
```
AC1014_from_autocad_2000.dwg:
```
Next object: 12 Handleoff: 0x1 [UMC] Offset: -2919 [MC] @19874
==========================================
Object number: 12/C, Size: 30 [MS], Type: 500 [BS], Address: 19876
Add object DICTIONARYWDFLT [12] Decode object DICTIONARYWDFLT
handle: 0.1.E [H 5]
EED[0] size: 0 (end)
num_eed: 0
bitsize: 164 [RL]
 Hdlsize: 0x4C, hdl_dat: @20.4 - @30.0 (30)
num_reactors: 1 [BL 0]
ownerhandle: (12.1.2) abs:12 [H 330]
reactors[0]: (4.1.C) abs:12 [H* 330] => DICTIONARY
xdicobjhandle: (3.0.0) abs:0 [H 360]
--common_size: 60
numitems: 1 [BL 0]
cloning: 1 [BS 281]
is_hardowner: 0x0 [RC 280]
texts[0]: "Normal" [TV 3]
itemhandles[0]: (2.1.F) abs:15 [H* 0]
defaultid: (5.1.F) abs:15 [H 340]
 padding: +4
 object_map{E} = 12
 padding: F5/5 (4 bits)
crc: BE26 [RSx]
 check_CRC 19874-19906 = 32: BE26 == BE26
```
AC1015_from_autocad_2000.dwg:
```
Next object: 12 Handleoff: 0x1 [UMC] Offset: -1451 [MC] @20458
==========================================
Object number: 12/C, Size: 30 [MS], Type: 500 [BS], Address: 20460
Add object DICTIONARYWDFLT [12] Decode object DICTIONARYWDFLT
bitsize: 164 [RL] @4.2
 Hdlsize: 0x4C, hdl_dat: @20.4 - @30.0 (30)
handle: 0.1.E [H 5]
EED[0] size: 0 (end)
num_eed: 0
num_reactors: 1 [BL 0]
ownerhandle: (12.1.2) abs:12 [H 330]
reactors[0]: (4.1.C) abs:12 [H* 330] => DICTIONARY
xdicobjhandle: (3.0.0) abs:0 [H 360]
--common_size: 60
numitems: 1 [BL 0]
cloning: 1 [BS 281]
is_hardowner: 0x0 [RC 280]
texts[0]: "Normal" [TV 3]
itemhandles[0]: (2.1.F) abs:15 [H* 0]
defaultid: (5.1.F) abs:15 [H 340]
 padding: +4
 object_map{E} = 12
 padding: F1/1 (4 bits)
crc: 77B7 [RSx]
 check_CRC 20458-20490 = 32: 77B7 == 77B7
```

**Comment by rurban** [comment]
OK, it's much simpler this way. Also according to the specs. 
Maybe we can simplify the DICTIONARY also

**Comment by michal-josef-spacek** [comment]
@rurban 
In case of DICTIONARY object:
* DXF is ok, both conditions are right.
* DWG is ok too (is_hardowner is in AC1014 and AC1015, cloning in AC1015 only).

I think that's everything is ok.

**Pull request merged**
