### PR TITLE
Fix UCS table

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by rurban** [comment]
I need to test this, as I had the very same idea, but found contradicting examples

**Comment by michal-josef-spacek** [comment]
> I need to test this, as I had the very same idea, but found contradicting examples

I think that's ok - based on fix with used in https://github.com/LibreDWG/libredwg/pull/620

**Comment by michal-josef-spacek** [comment]
> > I need to test this, as I had the very same idea, but found contradicting examples
> 
> I think that's ok - based on fix with used in #620

Ah, no.. Missing used in UCS.. I will fix

**Comment by rurban** [comment]
tested ok

**Pull request merged**
