### PR TITLE
Improve logging of text dashes

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
I think, that we could improve this. To something ```dashes[1].text: FOO [TF 9]```

**Comment by michal-josef-spacek** [comment]
Actual logging output:
```
...
strings_area: "FOO" [TF 256 0]
dashes[1].text: "FOO" [TF 3 9] @0
dashes[4].text: "BAR" [TF 3 9] @4
...
```

**Comment by rurban** [comment]
I'd rather like 
strings_area: "FOO\000BAR\000BAZ"

**Comment by michal-josef-spacek** [comment]
> I'd rather like
> strings_area: "FOO\000BAR\000BAZ"

no problem, but why not "FOO\0BAR" ?

**Comment by rurban** [comment]
> > I'd rather like
> > strings_area: "FOO\000BAR\000BAZ"
> 
> no problem, but why not "FOO\0BAR\0BAZ" ?

This would look nicer, but is invalid C. Only \000 or \x00 would do

**Comment by michal-josef-spacek** [comment]
We are talking about logging, this is for "user" :-) I don't understand C validity in this case.

**Comment by rurban** [comment]
Well, then go for it. Looks better

**Comment by rurban** [comment]
I"ve just fixed the asan issue with 17f95b23d07895ed289fbf1f6acbd4c792ace816, please rebase on latest master soon.

**Comment by michal-josef-spacek** [comment]
Done

**Pull request merged**
