### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
There was a trailing newline

### CODE REVIEW

**Review by rurban — CHANGES_REQUESTED** [review]
no, LOG_TRACE needs the \n

**Comment by michal-josef-spacek** [comment]
@rurban yes, I understand.
There is LOG_TRACE("\n") in LOG_RPOS
See https://github.com/LibreDWG/libredwg/blob/master/src/dec_macros.h#L55

**Comment by michal-josef-spacek** [comment]
I tested it.
Original output (dwgread -v3):
```
=======> Second Header 3 (start):    22690
pvzadr: 58b2
size: 114 [RL 0]
address: 0x58a2 [BLx 0]

version: AC1015 [TFF 12]
null_b[i]: 0 [B 0]
null_b[i]: 0 [B 0]
null_b[i]: 0 [B 0]
null_b[i]: 0 [B 0]
unknown_10: 0x10 [RC 0]
unknown_rc4[i]: 0x5c [RC 0]
unknown_rc4[i]: 0x18 [RC 0]
unknown_rc4[i]: 0x70 [RC 0]
unknown_rc4[i]: 0x1 [RC 0]
num_sections: 0x6 [RC 0]
section[i].nr: 0x0 [RC 0]
section[i].address: 0x49bf [BLx 0]

section[i].size: 600 [BL 0]
section[i].nr: 0x1 [RC 0]
section[i].address: 0x4c17 [BLx 0]

section[i].size: 190 [BL 0]
section[i].nr: 0x2 [RC 0]
section[i].address: 0x57fd [BLx 0]
...
```

After fix (dwgread -v3):
```
=======> Second Header 3 (start):    22690
pvzadr: 58b2
size: 114 [RL 0]
address: 0x58a2 [BLx 0]
version: AC1015 [TFF 12]
null_b[i]: 0 [B 0]
null_b[i]: 0 [B 0]
null_b[i]: 0 [B 0]
null_b[i]: 0 [B 0]
unknown_10: 0x10 [RC 0]
unknown_rc4[i]: 0x5c [RC 0]
unknown_rc4[i]: 0x18 [RC 0]
unknown_rc4[i]: 0x70 [RC 0]
unknown_rc4[i]: 0x1 [RC 0]
num_sections: 0x6 [RC 0]
section[i].nr: 0x0 [RC 0]
section[i].address: 0x49bf [BLx 0]
section[i].size: 600 [BL 0]
section[i].nr: 0x1 [RC 0]
section[i].address: 0x4c17 [BLx 0]
section[i].size: 190 [BL 0]
section[i].nr: 0x2 [RC 0]
section[i].address: 0x57fd [BLx 0]
...
```

**Review by rurban — APPROVED** [review]

**Comment by rurban** [comment]
Oh, I was confused. Thanks

**Pull request merged**
