### PR TITLE
Optimize dwg_add_Handleref

### PR DESCRIPTION
**Pull request by gongxy-sh**

### CODE REVIEW

**Review by rurban — CHANGES_REQUESTED** [review]
We already had that useful feature, but we still need your FSF copyright assignment

**Comment by rurban** [comment]
Gong Xiangyang's copyright assignment arrived, great!

**Comment by gongxy-sh** [comment]
OK.

**Review by rurban — APPROVED** [review]
LGTM and merges fine. Smoking now. 
bsearch_ex got more complex, sure, but still according to the standard. So it's fine

**Comment by rurban** [comment]
Merged. Big thanks!!

**Pull request closed without merging**
