### PR TITLE
Auxiliary functions for dwg R/W.

### PR DESCRIPTION
**Pull request by gongxy-sh**
dwg_new_Document0/dwg_free_Document for DWG reader.
dwg_free_Document for DWG writer.

### CODE REVIEW

**Review by rurban — APPROVED** [review]
Ok, fair enough.
dwg_free is exported, but this pleases our VBA naming style.

**Comment by gongxy-sh** [comment]
dwg_free_Document = dwg_free + free.

**Comment by gongxy-sh** [comment]
dwg_free_Document = dwg_free + free.

**Comment by gongxy-sh** [comment]
for reader
Dwg_Data *dwg  = dwg_new_Docment0(...);
dwg_read_file(...)
...
dwg_free_Document(dwg);

for writer
Dwg_Data *dwg  = dwg_new_Docment(...);
...
dwg_write_file(...)
dwg_free_Document(dwg);

**Pull request closed without merging**
