### PR TITLE
Fix unit mode header variable

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Review by rurban — APPROVED** [review]

**Comment by rurban** [comment]
RC for an RS?

**Comment by michal-josef-spacek** [comment]
> RC for an RS?

I don't know, I need to check a number of header variables and look at it again.
Actually, it's working

**Comment by rurban** [comment]
Not, it"s not working. Now I get UNITMODE 1 for r11/from_autocad_r12/sample/ files, which have clearly UNITMODE 0 in the DXF.

**Comment by michal-josef-spacek** [comment]
@rurban Which file? I looked to all files in this dir and seems ok.

**Comment by rurban** [comment]
TABLETAC and TABLET-B

**Comment by michal-josef-spacek** [comment]
I have TABLETAC dwg file with UNITMODE=1 and via r11 i generate DXF with same value.
Same for TABLET-B.

Output of TABLET-B.DWG:
```
SHADEDIF: 70 [RS 70]
unknown_59: 0 [RS 0]
UNITMODE: 1 [RS 70]
DEBUG_POS @1343.0 (10744)
00001C007EFD5742000000000000F03F000000000000F03F
  RS :0 / 0x0000 (16)

  RL :1835008 / 0x001c0000 (32)
  RD :412148564080.000000 (64)
```

**Comment by rurban** [comment]
yes, but the dxf has them with 0

**Comment by michal-josef-spacek** [comment]
TABLET-B.DXF output via R11:
```
$PLIMMAX
 10
12.0
 20
9.0
  9
$UNITMODE
 70
     1
  9
$VISRETAIN
 70
     0
  0
```

```dwgread -O DXF -o TABLET-B.dxf TABLET-B.DWG``` output:
```
$PLIMMAX
 10
12.0
 20
9.0
  9
$UNITMODE
 70
     1
  9
$VISRETAIN
 70
     0
  9
```

I don't see any issue :-)

**Comment by michal-josef-spacek** [comment]
I am checking these values with my https://github.com/michal-josef-spacek/CAD-Format-DWG-AC1009/blob/main/dwg_ac1009.ksy#L781 too.

**Comment by rurban** [comment]
I saw these UNITMODE DXF values with the ODA converter. Maybe an ODA bug.

**Pull request merged**
