### PR TITLE
WIP: Fix BLOCKSTRETCHACTION object

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
Alternative to https://github.com/LibreDWG/libredwg/pull/1054

**Comment by michal-josef-spacek** [comment]
Issues:
1) Logging

Actual situation:
```num_hdls: 3 [BL 73]
hdls[rcount1].hdl: (4.2.271) abs:625 [H 331]
hdls[0].num_indexes: 1 [BS 74]
indexes[0]: 1 [BL 94]
hdls[rcount1].hdl: (4.2.274) abs:628 [H 331]
hdls[1].num_indexes: 2 [BS 74]
indexes[0]: 0 [BL 94]
indexes[1]: 1 [BL 94]
...
```
Expected:
```
num_hdls: 3 [BL 73]
hdls[rcount1].hdl: (4.2.271) abs:625 [H 331]
hdls[0].num_indexes: 1 [BS 74]
hdls[0].indexes[0]: 1 [BL 94]
hdls[0].hdls[rcount1].hdl: (4.2.274) abs:628 [H 331]
hdls[1].num_indexes: 2 [BS 74]
hdls[0].indexes[0]: 0 [BL 94]
hdls[0].indexes[1]: 1 [BL 94]
```
I don't see, where is the issue. Problem of ```SUB_FIELD_VECTOR_INL```

2) dwg2dxf doesn't set the right index values. The actual result is 0 every time.

Issue of SUB_FIELD_VECTOR_INL ?

**Comment by rurban** [comment]
Still better than before

**Comment by michal-josef-spacek** [comment]
1) is blocked by https://github.com/LibreDWG/libredwg/issues/1056

**Comment by rurban** [comment]
Merged with fixes

**Comment by rurban** [comment]
Merged with fixes

**Pull request closed without merging**
