### PR TITLE
Fix issues in preR13 dimensions

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
Missing text_rotation in DIMENSION_ANG3PT

**Comment by rurban** [comment]
I think I handled all of them seperately by myself already

**Comment by michal-josef-spacek** [comment]
> I think I handled all of them seperately by myself already

No.
This example (https://github.com/LibreDWG/libredwg/issues/587#issuecomment-1397111833) not working.
Output:
```
Add entity DIMENSION_ANG2LN [13] ===========================
Entity number: 13, Type: 23, Addr: 6cf
flag_r11: 0x20 [RC 0]
          HAS_HANDLING (0x20)
size: 153 [RS]
layer: 0 [H(RSd) 8]
opts_r11: 0x847a [RSx 0]
          HAS_FLAG (0x2) HAS_DXF13 (0x8) HAS_DXF14 (0x10) HAS_DXF15 (0x20) HAS_ANGLES (0x40) HAS_DXF53 (0x400) HAS_DIMSTYLE (0x8000)
handle: 0.1.5B [H 5]
block: 0 [H(RSd) 2]
def_pt: (7.453637, 6.190869, 0.000000) [3RD 10]
text_midpt: (7.868650, 5.811528) [2RD 11]
flag: 0x85 [RC 70]
=> Entity DIMENSION_ANG3PT
xline1_pt: (6.060436, 6.406088, 0.000000) [3RD 13]
xline2_pt: (8.708595, 5.485104, 0.000000) [3RD 14]
center_pt: (9.208638, 7.694218, 0.000000) [3RD 15]
horiz_direction: 0.000000 [RD 51]
text_rotation: 0.000000 [RD 53]
dimstyle: -5163 [H(RSd) 0]
ERROR: offset 8
crc: 84D5 [RSx]
```
Missing right text_rotation and I am proposing to replace your "horiz_direction and text_rotation" to DXF 16.

**Comment by rurban** [comment]
Yes, mine looks wrong

**Review by rurban — CHANGES_REQUESTED** [review]
This is already in, and as hex

**Comment by michal-josef-spacek** [comment]
Great, thank you.

**Pull request closed without merging**
