### PR TITLE
Add missing macros for DWG to JSON conversions

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
Fixes two cases in https://github.com/LibreDWG/libredwg/issues/943

**Review by rurban — CHANGES_REQUESTED** [review]
0x hex numbers are invalid in json.

**Comment by rurban** [comment]
I fixed it better

**Comment by michal-josef-spacek** [comment]
Thank you

**Pull request closed without merging**
