### PR TITLE
Smoke/pre r13 foo

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
Fix PSLTSCALE and TREEDEPTH
Fix pre R_2_0 entities

### CODE REVIEW

**Comment by rurban** [comment]
I think most of it is already in. Can you rebase, or should I check?

**Comment by michal-josef-spacek** [comment]
@rurban I fixed conflicts

**Comment by rurban** [comment]
I've rebased it, and added the needed dynapi and tests.

**Comment by michal-josef-spacek** [comment]
@rurban great

**Comment by rurban** [comment]
LOAD still fails the unit-test, will look at it tommorrow

**Pull request closed without merging**
