### PR TITLE
Fix saving of last token in entity

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
In conversion from JSON to DWG was error with saving of last entity

### CODE REVIEW

**Comment by rurban** [comment]
=> heap-buffer-overflow in src/encode.c:1854 (encode_preR13_section_hdr)

**Comment by michal-josef-spacek** [comment]
> => heap-buffer-overflow in src/encode.c:1854 (encode_preR13_section_hdr) with entities_r10.json

hm, you are right

**Comment by rurban** [comment]
> > => heap-buffer-overflow in src/encode.c:1854 (encode_preR13_section_hdr) with entities_r10.json
> 
> hm, you are right

But on master also

**Comment by rurban** [comment]
Fixed now the overflows in injson r11 with smoke/alive

**Comment by michal-josef-spacek** [comment]
@rurban Actual smoke/alive (5600781291dbab1f42595564e619d209c49fd478) has issue:
Input: [foo.json.gz](https://github.com/LibreDWG/libredwg/files/11162483/foo.json.gz)
Command: ```dwgwrite -v9 foo.json```
Output:
```
...
dashes_r11: 0.000000 [RD]
ERROR: Unexpected UNDEFINED at 502 of 502 tokens, expected OBJECTS OBJECT. json_OBJECTS:2831
Skip JSON UNDEFINED  at 502 of 502 tokens

-keys: 0, object 10 of 12
ERROR: Unexpected end of JSON at 503 of 502 tokens
End of OBJECTS (hard error)

ERROR 0x800

Critical: INVALIDDWG
```

**Comment by rurban** [comment]
Merged my variant (which is the same as yours)

**Pull request closed without merging**
