### PR TITLE
Fix polyline 0x8000 flag

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
GH #548
Flag mean, that entity is replaced by entity in extra entity section. There are unknown data sometime

### CODE REVIEW

**Comment by rurban** [comment]
It could be the calculated curve fit pts

**Comment by michal-josef-spacek** [comment]
> It could be the calculated curve fit pts

Yes, I think too.

**Comment by michal-josef-spacek** [comment]
When I open this kind of file and save it again, entities were replaced.

**Comment by rurban** [comment]
You deleted the code to get the 2RD curve_fit pts. NOK

**Pull request closed without merging**
